# Generated by Django 3.0.4 on 2021-01-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAccount',
            fields=[
                ('UniId', models.AutoField(primary_key=True, serialize=False)),
                ('UniName', models.CharField(default='Uni Name', max_length=500)),
                ('UniUsername', models.CharField(default='Uni Username', max_length=100)),
                ('UniEmail', models.CharField(default='Uni Email', max_length=100)),
                ('UniPassword', models.TextField(default='Uni Password', max_length=3000)),
                ('UniAddress', models.CharField(default='Uni Address', max_length=100)),
                ('UniStatus', models.CharField(choices=[('Active', 'Active'), ('Disable', 'Disable')], default='Disable', max_length=80)),
                ('UniLogo', models.ImageField(default='logo.png', upload_to='university/')),
                ('SuperId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.AdminAccount')),
                ('UniPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityBranch',
            fields=[
                ('BranchId', models.AutoField(primary_key=True, serialize=False)),
                ('BranchName', models.CharField(default='Branch Name', max_length=400)),
                ('BranchUsername', models.CharField(default='Branch Username', max_length=400)),
                ('BranchEmail', models.CharField(default='Branch Email', max_length=400)),
                ('BranchPassword', models.TextField(default='Branch Password', max_length=3000)),
                ('BranchAddress', models.CharField(default='Branch Address', max_length=400)),
                ('BranchCreatedDate', models.DateTimeField(blank=True)),
                ('UniversityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
