# Generated by Django 3.0.4 on 2021-05-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitybranch',
            name='BranchCreatedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
