# Generated by Django 3.0.4 on 2020-12-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitybranch',
            name='BranchCreatedDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
