# Generated by Django 3.0.4 on 2021-01-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('role', models.CharField(default='null', max_length=50)),
                ('token', models.TextField(default=0)),
                ('verify', models.CharField(default='unverified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default='', max_length=150)),
                ('Email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(default='', max_length=100)),
                ('Message', models.TextField(default='dummy', max_length=1000)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
