# Generated by Django 3.0.4 on 2020-06-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='branchId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='uniId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
            preserve_default=False,
        ),
    ]
