# Generated by Django 3.0.4 on 2020-12-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversityApp', '0002_auto_20201203_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FianceUser',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='First Name', max_length=60)),
                ('LastName', models.CharField(default='Last Name', max_length=60)),
                ('Email', models.CharField(default='youremail@gmail.com', max_length=100)),
                ('Password', models.TextField(max_length=1300)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
