# Generated by Django 3.0.4 on 2020-12-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20201222_1606'),
        ('UniversityApp', '0002_auto_20201203_1600'),
        ('faculty', '0040_auto_20201222_1606'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('SalaryId', models.AutoField(primary_key=True, serialize=False)),
                ('IssueDate', models.DateTimeField(auto_now_add=True)),
                ('Salaryamount', models.IntegerField(default=0)),
                ('Salaryteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='StudetFee',
            fields=[
                ('FeeId', models.AutoField(primary_key=True, serialize=False)),
                ('IssueDate', models.DateTimeField(auto_now_add=True)),
                ('FeeAmount', models.IntegerField(default=0)),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
