# Generated by Django 3.0.4 on 2021-05-10 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20210109_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 855226)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 855226)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 863738)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 863738)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 855226)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 855226)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 866156)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 10, 31, 24, 866156)),
        ),
    ]
