# Generated by Django 3.0.4 on 2020-07-04 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0026_auto_20200703_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigmentmodel',
            name='Mark',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 45, 19, 527930)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 45, 19, 522933)),
        ),
    ]
