# Generated by Django 3.0.4 on 2020-07-04 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_auto_20200704_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 53, 22, 311246)),
        ),
        migrations.AddField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 53, 22, 310248)),
        ),
        migrations.AddField(
            model_name='assigmentmodel',
            name='Status',
            field=models.CharField(default='True', max_length=20),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 53, 22, 320247)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 12, 53, 22, 316245)),
        ),
    ]
