# Generated by Django 3.0.4 on 2020-07-06 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_auto_20200704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 12, 34, 23, 943805)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 12, 34, 23, 943805)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 12, 34, 23, 951804)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 12, 34, 23, 948804)),
        ),
    ]
