# Generated by Django 3.0.4 on 2020-07-09 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('faculty', '0032_auto_20200707_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 986086)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 986086)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 995350)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 990922)),
        ),
        migrations.CreateModel(
            name='MidtermModel',
            fields=[
                ('MidtermId', models.AutoField(primary_key=True, serialize=False)),
                ('MidtermTitle', models.CharField(default='Title', max_length=100)),
                ('MidtermDesc', models.TextField(default='Assigment Description', max_length=400)),
                ('MidtermFile', models.FileField(default='#', upload_to='Assigments/')),
                ('Mark', models.CharField(default='0', max_length=20)),
                ('StartDate', models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 987087))),
                ('EndDate', models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 987087))),
                ('Status', models.CharField(default='True', max_length=20)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FinalExamModel',
            fields=[
                ('FinalExamId', models.AutoField(primary_key=True, serialize=False)),
                ('FinalExamTitle', models.CharField(default='Title', max_length=100)),
                ('FinalExamDesc', models.TextField(default='Assigment Description', max_length=400)),
                ('FinalExamFile', models.FileField(default='#', upload_to='Assigments/')),
                ('Mark', models.CharField(default='0', max_length=20)),
                ('StartDate', models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 988904))),
                ('EndDate', models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 3, 47, 988904))),
                ('Status', models.CharField(default='True', max_length=20)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
