# Generated by Django 3.0.4 on 2020-07-09 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0034_auto_20200709_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_result',
            name='Grade',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='exam_result',
            name='Obtained_marks',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 16, 32, 21, 864083)),
        ),
    ]
