# Generated by Django 3.0.4 on 2020-07-10 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0035_auto_20200709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 774235)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 774235)),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='Status',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 777235)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 777235)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 775235)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 775235)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 782235)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 57, 12, 780238)),
        ),
    ]
