# Generated by Django 3.0.4 on 2021-01-05 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0040_auto_20201222_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinequiz',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 600255)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 600255)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 609231)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 609231)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 606238)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 606238)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 620201)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 15, 24, 4, 615214)),
        ),
    ]
