# Generated by Django 3.0.4 on 2021-01-05 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0002_auto_20201203_1600'),
        ('faculty', '0041_auto_20210105_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 846935)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 846935)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 848930)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 848930)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 847932)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 847932)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 852918)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 2, 19, 850924)),
        ),
        migrations.CreateModel(
            name='quaizsheet',
            fields=[
                ('sheetid', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.TextField(max_length='800')),
                ('q2', models.TextField(max_length='800')),
                ('q3', models.TextField(max_length='800')),
                ('q4', models.TextField(max_length='800')),
                ('currectAnswse', models.TextField(max_length='800')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.onlinequiz')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
