# Generated by Django 3.0.4 on 2021-01-05 16:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0042_auto_20210105_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quaizsheet',
            old_name='q1',
            new_name='a1',
        ),
        migrations.RenameField(
            model_name='quaizsheet',
            old_name='q2',
            new_name='a2',
        ),
        migrations.RenameField(
            model_name='quaizsheet',
            old_name='q3',
            new_name='a3',
        ),
        migrations.RenameField(
            model_name='quaizsheet',
            old_name='q4',
            new_name='a4',
        ),
        migrations.AddField(
            model_name='quaizsheet',
            name='question',
            field=models.TextField(default=django.utils.timezone.now, max_length='800'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 835857)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 835857)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 837851)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 837851)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 836854)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 836854)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 841841)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 840843)),
        ),
    ]
