# Generated by Django 3.0.4 on 2021-01-06 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0044_auto_20210106_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 771567)),
        ),
        migrations.AlterField(
            model_name='assigmentmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 771567)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 773561)),
        ),
        migrations.AlterField(
            model_name='finalexammodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 773561)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 772564)),
        ),
        migrations.AlterField(
            model_name='midtermmodel',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 772564)),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 777577)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 44, 57, 776580)),
        ),
    ]
