# Generated by Django 3.0.4 on 2021-01-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_title', models.CharField(default='', max_length=255)),
                ('Course_description', models.TextField(default=0)),
                ('Course_requirment', models.TextField(default=0)),
                ('Course_start_date', models.DateTimeField(auto_now_add=True)),
                ('Course_Price', models.TextField(default=0)),
                ('Course_Duration', models.TextField(default=0)),
                ('Course_Thumbnail', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('cattitle', models.CharField(default='', max_length=255)),
                ('catdesct', models.CharField(default='', max_length=255)),
                ('catimage', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('levelid', models.AutoField(primary_key=True, serialize=False)),
                ('leveltitle', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(default='Video Title', max_length=250)),
                ('videoFile', models.FileField(default='test.jpg', upload_to='videos/')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Occupation', models.CharField(default='', max_length=255)),
                ('Company_Name', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Personal_info', models.TextField(default='')),
                ('Facebook', models.URLField(default='', max_length=500)),
                ('Twitter', models.URLField(default='', max_length=500)),
                ('Linkedin', models.URLField(default='', max_length=500)),
                ('Google_Plus', models.URLField(default='', max_length=500)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.User_Signup')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseLevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='Course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.User_Signup'),
        ),
    ]
