# Generated by Django 3.0.4 on 2021-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categroypost',
            fields=[
                ('catPostId', models.AutoField(primary_key=True, serialize=False)),
                ('catTitle', models.CharField(default='Category title', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(default='', max_length=130)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
    ]
