# Generated by Django 3.0.4 on 2020-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventtitle', models.CharField(default='', max_length=255)),
                ('eventdesc', models.TextField()),
                ('eventstartdate', models.DateTimeField(blank=True)),
                ('eventenddate', models.DateTimeField(blank=True)),
                ('eventaddress', models.CharField(max_length=255)),
                ('eventmap', models.CharField(max_length=255)),
                ('eventemail', models.CharField(max_length=255)),
                ('eventcontactno', models.CharField(max_length=255)),
                ('eventtopics', models.TextField()),
                ('eventspeacker1', models.CharField(default='', max_length=100)),
                ('eventimg', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
    ]
