# Generated by Django 3.0.4 on 2021-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('SFname', models.CharField(default='First Name', max_length=100)),
                ('SLname', models.CharField(default='Last Name', max_length=100)),
                ('SEmail', models.CharField(default='Email Name', max_length=100)),
                ('SUsername', models.CharField(default='Username ', max_length=100)),
                ('SPassword', models.TextField(default='Password ', max_length=3000)),
                ('SContactNo', models.CharField(default='Contact no', max_length=100)),
                ('SProfile', models.ImageField(default='dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('PackId', models.AutoField(primary_key=True, serialize=False)),
                ('PackName', models.CharField(default='Package Name', max_length=300)),
                ('PackDescription', models.TextField(default='Package Description', max_length=3300)),
                ('PackStudent', models.IntegerField(default=0)),
                ('PackTeacher', models.IntegerField(default=0)),
                ('PackDurationStart', models.DateField()),
                ('PackDurationEnd', models.DateField()),
                ('PackPrice', models.FloatField(default=0.0)),
            ],
        ),
    ]
