# Generated by Django 3.0.4 on 2020-05-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('msgfrom', models.IntegerField()),
                ('msgto', models.IntegerField()),
                ('msg', models.TextField(max_length=3000)),
                ('sender_name', models.CharField(max_length=100)),
                ('is_read', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=100)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
