# Generated by Django 3.0.4 on 2021-01-09 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarModel',
            fields=[
                ('AcademicCalendarId', models.AutoField(primary_key=True, serialize=False)),
                ('AcademicCalendarTitle', models.CharField(default='Title', max_length=100)),
                ('AcademicCalendarDesc', models.TextField(default='Title', max_length=400)),
                ('AcademicCalendarStartDate', models.DateTimeField(auto_now_add=True)),
                ('AcademicCalendarEndDate', models.DateTimeField(auto_now_add=True)),
                ('AcademicCalendarLocation', models.CharField(default='Address', max_length=240)),
                ('Image', models.FileField(default='Notdata', upload_to='job')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationTitle', models.CharField(default='Notification Title', max_length=100)),
                ('NotificationDesc', models.TextField(default='Notification Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Schedule',
            fields=[
                ('Exam_Schedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 195402))),
                ('Exam_Schedule_File', models.FileField(default='Notdata', upload_to='semester_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Evaluation_Report',
            fields=[
                ('Faculty_Evaluation_Report_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Report_Name', models.CharField(default='Name', max_length=200)),
                ('Report_File', models.FileField(default='Notdata', upload_to='report')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAttendence',
            fields=[
                ('FacultyAttendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyAttendenceYear', models.TextField(default='December', max_length=50)),
                ('FacultyAttendenceMonth', models.TextField(default='April', max_length=50)),
                ('FacultyAttendencePresent', models.IntegerField(default=0)),
                ('FacultyAttendenceAbsent', models.IntegerField(default=0)),
                ('FacultyAttendenceTotal', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCalendarModel',
            fields=[
                ('FacultyCalendarId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyCalendarTitle', models.CharField(default='Title', max_length=100)),
                ('FacultyCalendarDesc', models.TextField(default='Title', max_length=400)),
                ('FacultyCalendarStartDate', models.DateTimeField(auto_now_add=True)),
                ('FacultyCalendarEndDate', models.DateTimeField(auto_now_add=True)),
                ('FacultyCalendarLocation', models.CharField(default='Address', max_length=240)),
                ('Image', models.FileField(default='Notdata', upload_to='job')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('FormId', models.AutoField(primary_key=True, serialize=False)),
                ('Formtitle', models.CharField(default='', max_length=100)),
                ('FormFile', models.FileField(default='Notdata', upload_to='forms')),
                ('FileCategory', models.CharField(choices=[('facultyguidline', 'Faculty Guidline'), ('applicationform', 'Application Forms'), ('thesisguidline', 'Thesis Guidline'), ('placementforms', 'Placement Forms'), ('cacforms', 'Cac Forms')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('MenuId', models.AutoField(primary_key=True, serialize=False)),
                ('MenuTitle', models.CharField(default='Menu Title', max_length=100)),
                ('MenuType', models.CharField(choices=[('Tea', 'Hi Tea'), ('lunchmedium', 'Lunch Medium Course'), ('Lunchnormalcourse', 'Lunch Normal Course')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOrders',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderParticipants', models.CharField(default='Participants', max_length=200)),
                ('OrderComments', models.TextField(default='Comments', max_length=350)),
                ('OrderList', models.TextField(default='Comments', max_length=450)),
                ('OrderStartDate', models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 193408))),
                ('OrderStartTime', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 193408))),
                ('OrderEndDate', models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 193408))),
                ('OrderEndTime', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 193408))),
            ],
        ),
        migrations.CreateModel(
            name='onlinesurvey',
            fields=[
                ('onlinesurvey_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_1', models.CharField(default='question1', max_length=200)),
                ('question_2', models.CharField(default='question2', max_length=200)),
                ('question_3', models.CharField(default='question3', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Placement_Portal',
            fields=[
                ('Placement_Portal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Job_Title', models.CharField(default='IT', max_length=200)),
                ('Name_of_Organization', models.CharField(default='xyz', max_length=200)),
                ('Company_Profile', models.CharField(default='Local', max_length=200)),
                ('Employment_Type', models.CharField(default='xyz', max_length=200)),
                ('Job_description', models.FileField(default='Notdata', upload_to='job')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('assistantteacher', 'Assistant Teacher'), ('teacher', 'Teacher'), ('professor', 'Professor'), ('assistantprofessor', 'Assistant Professor'), ('hod', 'HOD'), ('registrar', 'Registrar'), ('dean', 'Dean'), ('viceChancelor', 'ViceChancelor'), ('librarian', 'Librarian')], max_length=100)),
                ('active', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 190416))),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('ReservationId', models.AutoField(primary_key=True, serialize=False)),
                ('ReservationParticipants', models.CharField(default='Participants', max_length=200)),
                ('ReservationComments', models.TextField(default='Comments', max_length=350)),
                ('ReservationStartDate', models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 191416))),
                ('ReservationStartTime', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 191416))),
                ('ReservationEndDate', models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 191416))),
                ('ReservationEndTime', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 191416))),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('RoomId', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(default='Room Name', max_length=100)),
                ('RoomCode', models.CharField(default='Room Code', max_length=10)),
                ('RoomStatus', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Schedule',
            fields=[
                ('Semester_Schedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 18, 35, 31, 195402))),
                ('Semester_Schedule_File', models.FileField(default='Notdata', upload_to='semester_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('StudentAttendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentAttendenceYear', models.TextField(default='December', max_length=50)),
                ('StudentAttendenceMonth', models.TextField(default='April', max_length=50)),
                ('StudentAttendencePresent', models.IntegerField(default=0)),
                ('StudentAttendenceAbsent', models.IntegerField(default=0)),
                ('StudentAttendenceTotal', models.FloatField(default=0.0)),
            ],
        ),
    ]
