# Generated by Django 3.0.4 on 2020-05-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('faculty', '0001_initial'),
        ('administrator', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='Course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course'),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile'),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='semester_schedule',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='semester_schedule',
            name='Semester_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester'),
        ),
        migrations.AddField(
            model_name='semester_schedule',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='semester_schedule',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='RoomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Rooms'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='role',
            name='Instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor'),
        ),
        migrations.AddField(
            model_name='role',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='role',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='placement_portal',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='placement_portal',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='onlinesurvey',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='onlinesurvey',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='menuorders',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='menuorders',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='menu',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='form',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='form',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='facultycalendarmodel',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='facultycalendarmodel',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='facultycalendarmodel',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='facultyattendence',
            name='Instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor'),
        ),
        migrations.AddField(
            model_name='facultyattendence',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='facultyattendence',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='faculty_evaluation_report',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='faculty_evaluation_report',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='faculty_evaluation_report',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='Semester_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester'),
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='admin_notification',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
        ),
        migrations.AddField(
            model_name='admin_notification',
            name='Instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor'),
        ),
        migrations.AddField(
            model_name='admin_notification',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='admin_notification',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.AddField(
            model_name='academiccalendarmodel',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='academiccalendarmodel',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
    ]
