# Generated by Django 3.0.4 on 2020-06-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20200530_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendarmodel',
            name='AcademicCalendarEndDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academiccalendarmodel',
            name='AcademicCalendarStartDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 8, 15, 18, 24, 689080)),
        ),
        migrations.AlterField(
            model_name='facultycalendarmodel',
            name='FacultyCalendarEndDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facultycalendarmodel',
            name='FacultyCalendarStartDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 8, 15, 18, 24, 687081)),
        ),
    ]
