# Generated by Django 3.0.4 on 2020-06-20 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20200619_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 959651)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 952649)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 952649)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 952649)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 952649)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 948649)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 950650)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 950650)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 950650)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 950650)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 15, 1, 56, 957649)),
        ),
    ]
