# Generated by Django 3.0.4 on 2020-07-09 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_auto_20200709_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 340635)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 334465)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 334465)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 334465)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 334465)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 330440)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 333462)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 333462)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 333380)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 333380)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 340635)),
        ),
    ]
