# Generated by Django 3.0.4 on 2020-12-22 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_auto_20201221_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 907025)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 904095)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 904095)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 904095)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 904095)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 901163)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 902138)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 902138)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 902138)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 902138)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 22, 16, 6, 52, 906047)),
        ),
    ]
