# Generated by Django 3.0.4 on 2021-01-05 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0040_auto_20210105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 875748)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 873753)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 873753)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 872756)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 873753)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 870761)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 871758)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 871758)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 871758)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 871758)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 16, 12, 46, 875748)),
        ),
    ]
