# Generated by Django 3.0.4 on 2021-01-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0046_auto_20210106_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 259201)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 256210)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 256210)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 256210)),
        ),
        migrations.AlterField(
            model_name='menuorders',
            name='OrderStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 256210)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 253218)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 255212)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationEndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 255212)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 254215)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='ReservationStartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 254215)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 14, 52, 11, 259201)),
        ),
    ]
