# Generated by Django 3.0.4 on 2020-05-22 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='First Name', max_length=100)),
                ('Last_name', models.CharField(default='Last Name', max_length=100)),
                ('ContactNo', models.CharField(default='Contact No', max_length=100)),
                ('Address', models.CharField(default='Addresss', max_length=150)),
                ('DOB', models.DateField()),
                ('StudenBatch', models.CharField(default='Batch 1', max_length=50)),
                ('StudenShift', models.CharField(default='Morning', max_length=150)),
                ('Profile', models.ImageField(default='Thumb.jpg', upload_to='StudentProfile/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Appointment',
            fields=[
                ('Teacher_Appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Program', models.CharField(default='Program', max_length=100)),
                ('Department', models.CharField(default='Department', max_length=100)),
                ('Course', models.CharField(default='Course', max_length=100)),
                ('Teacher', models.CharField(default='Teacher', max_length=100)),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 11, 37, 35, 594691))),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Survey',
            fields=[
                ('Survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_1_Answer', models.CharField(default='agree', max_length=10)),
                ('question_2_Answer', models.CharField(default='notagree', max_length=10)),
                ('question_3_Answer', models.CharField(default='strongagree', max_length=10)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Submit_Evaluation',
            fields=[
                ('Student_Submit_Evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Student_Program', models.CharField(default='Program', max_length=100)),
                ('Report_File', models.FileField(default='Notdata', upload_to='report')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('verify', models.CharField(default='unverified', max_length=100)),
                ('role', models.CharField(default='null', max_length=50)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Query_Admin',
            fields=[
                ('queryid', models.AutoField(primary_key=True, serialize=False)),
                ('querytitle', models.CharField(default='Reason Title', max_length=50)),
                ('querymessage', models.TextField(default='Reason query', max_length=350)),
                ('querydate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 11, 37, 35, 586693))),
                ('querystatus', models.CharField(default='Pendding', max_length=30)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.AddField(
            model_name='student_profile',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Signup'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='branchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='uniId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount'),
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('Student_Course_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Courses', models.ManyToManyField(to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Assigment',
            fields=[
                ('Student_Assigment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Assigment_File', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 11, 37, 35, 595691))),
                ('roll', models.CharField(default='0', max_length=10)),
                ('section', models.CharField(default='xyz', max_length=10)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ScrunityForm',
            fields=[
                ('Scrunity_Form_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Program', models.CharField(default='Program', max_length=100)),
                ('Registration_no', models.CharField(default='0000000', max_length=100)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 11, 37, 35, 588694))),
                ('Scrunity_Rechecking', models.CharField(default='recheck', max_length=100)),
                ('Research_for_Evalution', models.CharField(default='evaluation', max_length=300)),
                ('Voucher_Number', models.CharField(default='number', max_length=100)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Student_Registration_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Registration_Code', models.CharField(default='000000', max_length=50)),
                ('Student_Program', models.CharField(default='Program', max_length=50)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAppointment',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('Job_Apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Program', models.CharField(default='Program', max_length=100)),
                ('Job_Experirnce', models.TextField(default='0', max_length=10)),
                ('Cv', models.FileField(default='Notdata', upload_to='cv')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicationTitle', models.CharField(default='Reason Title', max_length=50)),
                ('ApplicationMessage', models.TextField(default='Reason application', max_length=350)),
                ('ApplicationAttachment', models.FileField(default='reason.pdf', upload_to='ApplicationAttachment/')),
                ('ApplicationDate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 11, 37, 35, 582694))),
                ('ApplicationStatus', models.CharField(default='Pendding', max_length=30)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
