# Generated by Django 3.0.4 on 2020-06-16 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_auto_20200616_1859'),
        ('student', '0013_auto_20200616_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='Department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_profile',
            name='Semester_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 18, 59, 14, 627684)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 18, 59, 14, 634212)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 18, 59, 14, 643808)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 18, 59, 14, 631616)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 18, 59, 14, 641175)),
        ),
    ]
