# Generated by Django 3.0.4 on 2020-06-16 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('student', '0014_auto_20200616_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 3, 18, 616545)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 3, 18, 625674)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 3, 18, 636620)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 3, 18, 623626)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 3, 18, 635619)),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('Batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('Batch_Name', models.CharField(default='Batch_Name', max_length=100)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
