# Generated by Django 3.0.4 on 2020-06-16 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200616_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 5, 0, 365977)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 5, 0, 377840)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 5, 0, 390909)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 5, 0, 373719)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 5, 0, 389911)),
        ),
    ]
