# Generated by Django 3.0.4 on 2020-06-16 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200616_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course',
            name='StudenBatch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 10, 20, 642072)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 10, 20, 648073)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 10, 20, 654071)),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='StudenBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Batch'),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 10, 20, 646072)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 10, 20, 653071)),
        ),
    ]
