# Generated by Django 3.0.4 on 2020-06-16 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('student', '0017_auto_20200616_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 22, 46, 572499)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 22, 46, 577434)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 22, 46, 583432)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 22, 46, 575433)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 16, 19, 22, 46, 582431)),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section_id', models.AutoField(primary_key=True, serialize=False)),
                ('Section_Name', models.CharField(choices=[('Section_a', 'Section_A'), ('Section_b', 'Section_B'), ('Section_c', 'Section_C'), ('Section_d', 'Section_D'), ('Section_e', 'Section_E'), ('Section_f', 'Section_F')], max_length=100)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
