# Generated by Django 3.0.4 on 2020-07-03 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200620_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 2, 40, 630400)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 2, 40, 635365)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 2, 40, 642457)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 2, 40, 635365)),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_1_Answer',
            field=models.CharField(default='agree', max_length=12),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_2_Answer',
            field=models.CharField(default='notagree', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 2, 40, 641450)),
        ),
    ]
