# Generated by Django 3.0.4 on 2020-07-03 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200703_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 5, 38, 243243)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 5, 38, 251910)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 5, 38, 261255)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 5, 38, 248865)),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_1_Answer',
            field=models.CharField(default='agree', max_length=15),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_2_Answer',
            field=models.CharField(default='notagree', max_length=15),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_3_Answer',
            field=models.CharField(default='strongagree', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 15, 5, 38, 260256)),
        ),
    ]
