# Generated by Django 3.0.4 on 2020-07-04 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20200704_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assigment',
            name='Mark',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='student_assigment',
            name='Teacher_Upload',
            field=models.FileField(default='Notdata', upload_to='studentassigment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 13, 10, 21, 928475)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 13, 10, 21, 935492)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 13, 10, 21, 942479)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 13, 10, 21, 933475)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 13, 10, 21, 941475)),
        ),
    ]
