# Generated by Django 3.0.4 on 2020-07-07 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0032_auto_20200707_1644'),
        ('student', '0029_auto_20200707_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assigment',
            name='AsssigmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.AssigmentModel'),
        ),
        migrations.AddField(
            model_name='student_assigment',
            name='Status',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 16, 44, 25, 650036)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 16, 44, 25, 706127)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 16, 44, 25, 724711)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 16, 44, 25, 672265)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 16, 44, 25, 722186)),
        ),
    ]
