# Generated by Django 3.0.4 on 2020-07-09 07:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
        ('faculty', '0034_auto_20200709_1209'),
        ('student', '0031_auto_20200709_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 293318)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 302534)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 308991)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 297153)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 307976)),
        ),
        migrations.CreateModel(
            name='Student_Midterm',
            fields=[
                ('Student_Midterm_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Midterm_File', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 310686))),
                ('roll', models.CharField(default='0', max_length=10)),
                ('section', models.CharField(default='xyz', max_length=10)),
                ('Teacher_Upload', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Mark', models.CharField(default=0, max_length=20)),
                ('Status', models.CharField(default='False', max_length=20)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('MidtermId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.MidtermModel')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student_FinalExam',
            fields=[
                ('Student_FinalExam_Id', models.AutoField(primary_key=True, serialize=False)),
                ('FinalExam_File', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 12, 9, 29, 313533))),
                ('roll', models.CharField(default='0', max_length=10)),
                ('section', models.CharField(default='xyz', max_length=10)),
                ('Teacher_Upload', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Mark', models.CharField(default=0, max_length=20)),
                ('Status', models.CharField(default='False', max_length=20)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('FinalExamId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.FinalExamModel')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
