# Generated by Django 3.0.4 on 2021-01-06 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_auto_20210106_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 383037)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 392013)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 402984)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 407973)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 406974)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 388024)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 15, 52, 5, 399991)),
        ),
    ]
