# Generated by Django 3.0.4 on 2021-01-07 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0002_auto_20201203_1600'),
        ('faculty', '0056_auto_20210107_1741'),
        ('student', '0054_auto_20210106_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 473530)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 500733)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 500733)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 500733)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 500733)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 495260)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 17, 41, 14, 500733)),
        ),
        migrations.CreateModel(
            name='StudentQuizResult',
            fields=[
                ('qId', models.AutoField(primary_key=True, serialize=False)),
                ('totalmarks', models.IntegerField()),
                ('totalquestion', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('score', models.IntegerField()),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityBranch')),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.onlinequiz')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Signup')),
                ('uniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.UniversityAccount')),
            ],
        ),
    ]
