# Generated by Django 3.0.4 on 2021-01-08 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_auto_20210107_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizresult',
            name='attendstatus',
            field=models.CharField(default='True', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 963167)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 967157)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 971146)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 973141)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 972143)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 965162)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 6, 8, 970149)),
        ),
    ]
