# Generated by Django 3.0.4 on 2021-01-08 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_auto_20210108_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizresult',
            name='attendstatus',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 514406)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 521218)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 526682)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 527678)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 527678)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 520220)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 16, 18, 2, 521218)),
        ),
    ]
