# Generated by Django 3.0.4 on 2021-01-08 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_auto_20210108_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 49889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 49889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 57883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 57883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 57883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 49889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 15, 36, 41, 57883, tzinfo=utc)),
        ),
    ]
