# Generated by Django 3.0.4 on 2021-01-08 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_auto_20210108_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 253930)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 261933)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 271818)),
        ),
        migrations.AlterField(
            model_name='student_finalexam',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 271818)),
        ),
        migrations.AlterField(
            model_name='student_midterm',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 271818)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 261933)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 8, 20, 38, 37, 271818)),
        ),
    ]
